### ISSUE TITLE
Update ITs to be compatible with Docker machine

### ISSUE THREAD

**Issue by emetsger** [OA-PASS/pass-authz#75]
Running ITs against docker-machine results in test failures, but they succeed in Travis and non-docker-machine environments.

For example, `mvn clean install -DES_HOST=192.168.99.100 -DFCREPO_HOST=192.168.99.100 -DJMS_HOST=192.168.99.100` fails a number of tests:

```
 cat pass-authz-integration/target/failsafe-reports/org.dataconservancy.pass.authz.PassAuthzIT.txt pass-authz-integration/target/failsafe-reports/org.dataconservancy.pass.authz.PolicyListenerIT.txt pass-authz-integration/target/failsafe-reports/org.dataconservancy.pass.authz.UserServiceIT.txt
-------------------------------------------------------------------------------
Test set: org.dataconservancy.pass.authz.PassAuthzIT
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.458 s <<< FAILURE! - in org.dataconservancy.pass.authz.PassAuthzIT
userBasedPermissionIT(org.dataconservancy.pass.authz.PassAuthzIT)  Time elapsed: 5.536 s  <<< FAILURE!
java.lang.AssertionError: 
Http request failed: HTTP/1.1 403 ; 
Read authz: @prefix premis:  <http://www.loc.gov/premis/rdf/v1#> .
@prefix test:  <info:fedora/test/> .
@prefix pass:  <http://oapass.org/ns/pass#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix webac:  <http://fedora.info/definitions/v4/webac#> .
@prefix acl:  <http://www.w3.org/ns/auth/acl#> .
@prefix xsi:  <http://www.w3.org/2001/XMLSchema-instance> .
@prefix xmlns:  <http://www.w3.org/2000/xmlns/> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora:  <http://fedora.info/definitions/v4/repository#> .
@prefix xml:  <http://www.w3.org/XML/1998/namespace> .
@prefix dcjsonld:  <http://dataconservancy.org/ns/jsonld#> .
@prefix ebucore:  <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#> .
@prefix ldp:  <http://www.w3.org/ns/ldp#> .
@prefix xs:  <http://www.w3.org/2001/XMLSchema> .
@prefix fedoraconfig:  <http://fedora.info/definitions/v4/config#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix dc:  <http://purl.org/dc/elements/1.1/> .
@prefix authz:  <http://fedora.info/definitions/v4/authorization#> .

<http://192.168.99.100:57703/fcrepo/rest/acls/b9/30/46/54/b9304654-2507-4ebb-9952-346664730c1a/Read>
        rdf:type               fedora:Container ;
        rdf:type               acl:Authorization ;
        rdf:type               fedora:Resource ;
        acl:accessTo           <http://192.168.99.100:57703/fcrepo/rest/grants/8c/d9/d4/11/8cd9d411-66bf-4506-b1b5-4764e9d59414> ;
        fedora:lastModifiedBy  "fedoraAdmin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:createdBy       "fedoraAdmin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:created         "2018-11-14T13:36:16.64Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        fedora:lastModified    "2018-11-14T13:36:19.647Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        acl:mode               acl:Read ;
        rdf:type               ldp:RDFSource ;
        rdf:type               ldp:Container ;
        fedora:writable        "true"^^<http://www.w3.org/2001/XMLSchema#boolean> ;
        fedora:hasParent       <http://192.168.99.100:57703/fcrepo/rest/acls/b9/30/46/54/b9304654-2507-4ebb-9952-346664730c1a> .

Write authz: @prefix premis:  <http://www.loc.gov/premis/rdf/v1#> .
@prefix test:  <info:fedora/test/> .
@prefix pass:  <http://oapass.org/ns/pass#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix webac:  <http://fedora.info/definitions/v4/webac#> .
@prefix acl:  <http://www.w3.org/ns/auth/acl#> .
@prefix xsi:  <http://www.w3.org/2001/XMLSchema-instance> .
@prefix xmlns:  <http://www.w3.org/2000/xmlns/> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora:  <http://fedora.info/definitions/v4/repository#> .
@prefix xml:  <http://www.w3.org/XML/1998/namespace> .
@prefix dcjsonld:  <http://dataconservancy.org/ns/jsonld#> .
@prefix ebucore:  <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#> .
@prefix ldp:  <http://www.w3.org/ns/ldp#> .
@prefix xs:  <http://www.w3.org/2001/XMLSchema> .
@prefix fedoraconfig:  <http://fedora.info/definitions/v4/config#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix dc:  <http://purl.org/dc/elements/1.1/> .
@prefix authz:  <http://fedora.info/definitions/v4/authorization#> .

<http://192.168.99.100:57703/fcrepo/rest/acls/b9/30/46/54/b9304654-2507-4ebb-9952-346664730c1a/Write>
        rdf:type               fedora:Container ;
        rdf:type               acl:Authorization ;
        rdf:type               fedora:Resource ;
        fedora:lastModifiedBy  "fedoraAdmin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        acl:mode               acl:Write ;
        acl:mode               acl:Read ;
        acl:accessTo           <http://192.168.99.100:57703/fcrepo/rest/grants/8c/d9/d4/11/8cd9d411-66bf-4506-b1b5-4764e9d59414> ;
        acl:agent              <http://192.168.99.100:57703/fcrepo/rest/users/b0/5e/af/69/b05eaf69-9c54-4680-ad9b-4ff670f9164b> ;
        fedora:createdBy       "fedoraAdmin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:created         "2018-11-14T13:36:16.461Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        fedora:lastModified    "2018-11-14T13:36:19.487Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        acl:agent              <test:nobody> ;
        rdf:type               ldp:RDFSource ;
        rdf:type               ldp:Container ;
        fedora:writable        "true"^^<http://www.w3.org/2001/XMLSchema#boolean> ;
        fedora:hasParent       <http://192.168.99.100:57703/fcrepo/rest/acls/b9/30/46/54/b9304654-2507-4ebb-9952-346664730c1a> .

Root acl resourcehttp://192.168.99.100:57703/fcrepo/rest/.acl:
@prefix premis:  <http://www.loc.gov/premis/rdf/v1#> .
@prefix test:  <info:fedora/test/> .
@prefix pass:  <http://oapass.org/ns/pass#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix webac:  <http://fedora.info/definitions/v4/webac#> .
@prefix acl:  <http://www.w3.org/ns/auth/acl#> .
@prefix xsi:  <http://www.w3.org/2001/XMLSchema-instance> .
@prefix xmlns:  <http://www.w3.org/2000/xmlns/> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora:  <http://fedora.info/definitions/v4/repository#> .
@prefix xml:  <http://www.w3.org/XML/1998/namespace> .
@prefix dcjsonld:  <http://dataconservancy.org/ns/jsonld#> .
@prefix ebucore:  <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#> .
@prefix ldp:  <http://www.w3.org/ns/ldp#> .
@prefix xs:  <http://www.w3.org/2001/XMLSchema> .
@prefix fedoraconfig:  <http://fedora.info/definitions/v4/config#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix dc:  <http://purl.org/dc/elements/1.1/> .
@prefix authz:  <http://fedora.info/definitions/v4/authorization#> .

<http://192.168.99.100:57703/fcrepo/rest/.acl>
        rdf:type               fedora:Container ;
        rdf:type               fedora:Resource ;
        rdf:type               webac:Acl ;
        fedora:lastModifiedBy  "fedoraAdmin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:createdBy       "bootstrap"^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:created         "2018-09-19T15:00:06.348Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        fedora:lastModified    "2018-11-14T13:36:06.298Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        rdf:type               ldp:RDFSource ;
        rdf:type               ldp:Container ;
        fedora:writable        "true"^^<http://www.w3.org/2001/XMLSchema#boolean> ;
        fedora:hasParent       <http://192.168.99.100:57703/fcrepo/rest/> ;
        ldp:contains           <http://192.168.99.100:57703/fcrepo/rest/.acl/Read> ;
        ldp:contains           <http://192.168.99.100:57703/fcrepo/rest/.acl/Write> .

Root acl resourcehttp://192.168.99.100:57703/fcrepo/rest/.acl/Read:
@prefix premis:  <http://www.loc.gov/premis/rdf/v1#> .
@prefix test:  <info:fedora/test/> .
@prefix pass:  <http://oapass.org/ns/pass#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix webac:  <http://fedora.info/definitions/v4/webac#> .
@prefix acl:  <http://www.w3.org/ns/auth/acl#> .
@prefix xsi:  <http://www.w3.org/2001/XMLSchema-instance> .
@prefix xmlns:  <http://www.w3.org/2000/xmlns/> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora:  <http://fedora.info/definitions/v4/repository#> .
@prefix xml:  <http://www.w3.org/XML/1998/namespace> .
@prefix dcjsonld:  <http://dataconservancy.org/ns/jsonld#> .
@prefix ebucore:  <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#> .
@prefix ldp:  <http://www.w3.org/ns/ldp#> .
@prefix xs:  <http://www.w3.org/2001/XMLSchema> .
@prefix fedoraconfig:  <http://fedora.info/definitions/v4/config#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix dc:  <http://purl.org/dc/elements/1.1/> .
@prefix authz:  <http://fedora.info/definitions/v4/authorization#> .

<http://192.168.99.100:57703/fcrepo/rest/.acl/Read>
        rdf:type               fedora:Container ;
        rdf:type               acl:Authorization ;
        rdf:type               fedora:Resource ;
        acl:accessTo           <http://192.168.99.100:57703/fcrepo/rest/> ;
        fedora:lastModifiedBy  "fedoraAdmin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:createdBy       "fedoraAdmin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:created         "2018-11-14T13:35:50.062Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        fedora:lastModified    "2018-11-14T13:36:06.187Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        acl:mode               acl:Read ;
        acl:agent              <http://oapass.org/ns/roles/johnshopkins.edu#submitter> ;
        acl:agent              <http://oapass.org/ns/roles/johnshopkins.edu#admin> ;
        acl:agent              <http://oapass.org/ns/roles/johnshopkins.edu#pass-backend> ;
        rdf:type               ldp:RDFSource ;
        rdf:type               ldp:Container ;
        fedora:writable        "true"^^<http://www.w3.org/2001/XMLSchema#boolean> ;
        fedora:hasParent       <http://192.168.99.100:57703/fcrepo/rest/.acl> .

Root acl resourcehttp://192.168.99.100:57703/fcrepo/rest/.acl/Write:
@prefix premis:  <http://www.loc.gov/premis/rdf/v1#> .
@prefix test:  <info:fedora/test/> .
@prefix pass:  <http://oapass.org/ns/pass#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix webac:  <http://fedora.info/definitions/v4/webac#> .
@prefix acl:  <http://www.w3.org/ns/auth/acl#> .
@prefix xsi:  <http://www.w3.org/2001/XMLSchema-instance> .
@prefix xmlns:  <http://www.w3.org/2000/xmlns/> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix fedora:  <http://fedora.info/definitions/v4/repository#> .
@prefix xml:  <http://www.w3.org/XML/1998/namespace> .
@prefix dcjsonld:  <http://dataconservancy.org/ns/jsonld#> .
@prefix ebucore:  <http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#> .
@prefix ldp:  <http://www.w3.org/ns/ldp#> .
@prefix xs:  <http://www.w3.org/2001/XMLSchema> .
@prefix fedoraconfig:  <http://fedora.info/definitions/v4/config#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix dc:  <http://purl.org/dc/elements/1.1/> .
@prefix authz:  <http://fedora.info/definitions/v4/authorization#> .

<http://192.168.99.100:57703/fcrepo/rest/.acl/Write>
        rdf:type               fedora:Container ;
        rdf:type               acl:Authorization ;
        rdf:type               fedora:Resource ;
        acl:accessTo           <http://192.168.99.100:57703/fcrepo/rest/> ;
        fedora:lastModifiedBy  "fedoraAdmin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:createdBy       "fedoraAdmin"^^<http://www.w3.org/2001/XMLSchema#string> ;
        fedora:created         "2018-11-14T13:36:06.217Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        fedora:lastModified    "2018-11-14T13:36:06.217Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> ;
        acl:mode               acl:Write ;
        acl:mode               acl:Read ;
        rdf:type               ldp:RDFSource ;
        rdf:type               ldp:Container ;
        fedora:writable        "true"^^<http://www.w3.org/2001/XMLSchema#boolean> ;
        fedora:hasParent       <http://192.168.99.100:57703/fcrepo/rest/.acl> .


 <!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Forbidden</p><p><b>Description</b> The server understood the request but refuses to authorize it.</p><hr class="line" /><h3>Apache Tomcat/8.5.31</h3></body></html>
	at org.dataconservancy.pass.authz.PassAuthzIT.lambda$userBasedPermissionIT$4(PassAuthzIT.java:138)
	at org.dataconservancy.pass.authz.PassAuthzIT.userBasedPermissionIT(PassAuthzIT.java:137)

-------------------------------------------------------------------------------
Test set: org.dataconservancy.pass.authz.PolicyListenerIT
-------------------------------------------------------------------------------
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 37.064 s <<< FAILURE! - in org.dataconservancy.pass.authz.PolicyListenerIT
submissionOnlyEditableByCreatorTest(org.dataconservancy.pass.authz.PolicyListenerIT)  Time elapsed: 11.579 s  <<< FAILURE!
java.lang.AssertionError: <!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Forbidden</p><p><b>Description</b> The server understood the request but refuses to authorize it.</p><hr class="line" /><h3>Apache Tomcat/8.5.31</h3></body></html> expected:<204> but was:<403>
	at org.dataconservancy.pass.authz.PolicyListenerIT.doPatch(PolicyListenerIT.java:374)
	at org.dataconservancy.pass.authz.PolicyListenerIT.tryModifySubmission(PolicyListenerIT.java:341)
	at org.dataconservancy.pass.authz.PolicyListenerIT.submissionOnlyEditableByCreatorTest(PolicyListenerIT.java:200)

-------------------------------------------------------------------------------
Test set: org.dataconservancy.pass.authz.UserServiceIT
-------------------------------------------------------------------------------
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.08 s <<< FAILURE! - in org.dataconservancy.pass.authz.UserServiceIT
tokenAfterLoginTest(org.dataconservancy.pass.authz.UserServiceIT)  Time elapsed: 1.38 s  <<< FAILURE!
java.lang.AssertionError: Failed writing to http://192.168.99.100:57703/fcrepo/rest/submissions/07/ac/6a/56/07ac6a56-e339-483e-b82e-d0ee8044df00 expected:<201> but was:<403>
	at org.dataconservancy.pass.authz.UserServiceIT.doTokenTest(UserServiceIT.java:213)
	at org.dataconservancy.pass.authz.UserServiceIT.tokenAfterLoginTest(UserServiceIT.java:142)

$
```

**Comment by emetsger** [comment]
Resolved in #88
